platform :ios, '7.0'
pod 'SlimeRefresh'
pod 'SwipeView'
pod 'MJRefresh'
pod 'FMDB'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'SlimeRefresh'
pod 'NSStringEmojize'
pod 'JSBadgeView'
pod 'BCGenieEffect'
pod 'MTMigration'
pod 'RegexKitLite'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'UIImage-Categories'
pod 'MJExtension'
pod 'SWTableViewCell'